umccr/RNAsum

rmd_files/RNAseq_report.Rmd
=> Add separators between sections if no WGS data is provided

rmd_files/RNAseq_report.R, rmd_files/RNAseq_report.Rmd
* Solves #35 (at least for this case - I'll leave this PR as a draft until Jacek has a chance to look at it)
* Expanded param list for easier debugging
=> Fix circos plotting

README.md
Added instructions for running RNAsum via AWS-Batch
=> Update ReadMe 

rmd_files/RNAseq_report.Rmd
Attempt to resolve https://github.com/umccr/RNAsum/issues/49.
It'd be great if you can test it with your set-up of different input combinations (Dragen-v3.9/Arriba, Dragen-v3.7/Arriba, Dragen-v*/withoutArriba, bcbio) to make sure the code changes work for your various requirements.
=> resolve issue#49 with Dragen-v3.7 only inputs

rmd_files/RNAseq_report.Rmd
Reference: https://trello.com/c/Rau1zo9S/1240-add-of-wts-reads-to-rnasum-report
The Trello card has attached screenshot that shows how it'll be displayed.
=> Add library size information in the report

rmd_files/RNAseq_report.Rmd
Fixed following issues:
- https://github.com/umccr/RNAsum/issues/70
- https://github.com/umccr/RNAsum/issues/68
=> Report updates

rmd_files/RNAseq_report.Rmd
**Changes**
- Use gene level counts if provided as input
- Otherwise fall-back to previous approach to use transcript level counts and txi
The results have been verified and tested with https://github.com/umccr/WTS_workflow_results_comparison/blob/master/WTS_bcbio_VS_dragen.Rmd
=> Use dragen-gene quant output

rmd_files/RNAseq_report.Rmd
Update check to read in kallisto input if provided.
While testing against test data in `/data/test_data/final/test_sample_WTS`, I was getting error for sunburst_plot:
```
Error in if (!is.na(sunburst_plot[[2]])) { : the condition has length > 1
```
To resolve the issue, I have updated check to look for specific element in sublist. Think this was a warning in previous versions of R but now produces an error.
At [line 1304](https://github.com/umccr/RNAsum/compare/fix_issue_75?expand=1#diff-10a626899fa0f1760d680ae0c2e42a9651988dabeb89a11185f0f7f0f3a57491R1304), I was hitting:
```
R argument is of length zero
``` 
Think this was the issue here https://stackoverflow.com/questions/27350636/argument-is-of-length-zero-in-if-statement.
Using `isTRUE` resolves it.
=> Fixes https://github.com/umccr/RNAsum/issues/75

rmd_files/RNAseq_report.Rmd
Fix https://github.com/umccr/RNAsum/pull/76#discussion_r1032317013 and https://github.com/umccr/RNAsum/pull/76#discussion_r1032317429
=> Fix sunburst plot check

rmd_files/RNAseq_report.Rmd
- Resolves https://github.com/umccr/RNAsum/issues/90
- Tried to introduce minimal updates to Master code base. 
- Tested locally with following combination of fusions inputs
- fusions called by both Dragen and Arriba
- fusions called by only Dragen
- fusions called by only Arriba
- no fusions called by either Dragen or Arriba
- Next step will be to test on ICA with updated docker image
=> Fix fusion prep from Dragen and Arriba inputs

rmd_files/RNAseq_report.Rmd
Thanks @pdiakumis. This change resolves an issue that I came across while testing your changes at `issues/93-dtchrome` locally with my setup.
Just needed testing with multiple combination of inputs and some debugging.
Hopefully, this will cover most use cases that I know of (to the best of my knowledge).
=> Fix cell colouring for data other than CN

.github/workflows/build_and_push_container_to_ghcrio.yml
* Updated ::set-output syntax to $GITHUB_OUTPUT syntax
* Update docker/* actions to latest versions
* setup-qemu-action: v1 -> v2
* setup-buildx-action: v1 -> v2
* login-action: v1 -> v2
* build-push-action: v2 -> v4
* Set provenance to false to prevent creation of attestation manifest
Fixes https://github.com/umccr/RNAsum/issues/98
=> Docker Buildx GH Actions update

R/salmon.R
Fixes https://github.com/umccr/RNAsum/issues/110
=> Remove version from ensembl gene names

R/salmon.R
Fixes https://github.com/umccr/RNAsum/issues/110#issuecomment-1663295638
=> filter gene names with "PAR_Y"

R/fusions.R, inst/rmd/rnasum.Rmd
Fixes #112 (again) (hopefully!)
=> Handle empty Arriba but non-empty Dragen fusions

rmd_files/RNAseq_report.Rmd
Fixes https://github.com/umccr/RNAsum/issues/110 in master branch
=> Remove versions from gene names and PAR-Y contigs

rmd_files/RNAseq_report.Rmd
Fixes https://github.com/umccr/RNAsum/issues/109
Tested with 3 recent cases locally. 
Next, I'll run couple tests in ICA-dev, once RNAsum docker image has been updated.
=> Update run chunk condition

inst/rmd/rnasum.Rmd
Tested locally and the change works.
=> Fix Ensembl RDS parsing

R/sample_data.R
Closes https://github.com/umccr/RNAsum/issues/137
Tested using both `salmon` and `dragen_wts_dir` directory locally.
=> Include a check for quant.sf file

R/sv.R
=> manta: bind_rows handles NULL better

deploy/conda/recipe/meta.yaml
Adding back gpgr dependency to see if the plotting issues of #147 get resolved.
=> Add back gpgr dependency

.Rbuildignore, DESCRIPTION, deploy/conda/recipe/meta.yaml, inst/rmd/rnasum.Rmd
=> Add ragg dependency

DESCRIPTION, R/fusions.R, R/utils_shortcuts.R, inst/rmd/rnasum.Rmd
Fixes #153.
Also removing some dependencies which were required for the Ensembl data RDS (https://github.com/umccr/RNAsum.data/pull/3).
And adding a fix in `R/utils_shortcuts.R` for the `Namespace in Imports field not imported from:` NOTE from `devtools::check`.
=> Arrange fusions df

README.Rmd, README.md
Need to exclusively work with `README.Rmd` and remember to render that to generate the `README.md` file.
=> Sync READMEs

README.Rmd, README.md, inst/articles/TCGA_projects_summary.md, inst/articles/report_structure.md, inst/articles/workflow.md
- Fixed readme links
- Added support documents
=> Update links in the Readme

README.Rmd, README.md, inst/CITATION
- added citation file
- updated readme
=> Initialise citation file

inst/rmd/rnasum.Rmd, inst/scripts/icav1_download_and_run.R
See https://umccr.slack.com/archives/C04F5SMUH8C/p1726445326976579 and https://umccr.slack.com/archives/C016A5BSKRC/p1726446538392299
=> Handle edge case when no tiered PCGR variants

inst/rmd/rnasum.Rmd, inst/scripts/icav2_download_and_run.R
Fixes #180.
Basically checking if the remaining CN gains/losses are non-zero before we evaluate their respective chunks.
Also adding script to download required S3 inputs for a failed RNAsum ICAv2 run.
=> Handle zero CN gains/losses

R/barPlot.R, R/cdfPlot.R, R/combineDatasets.R, R/exprGroupsStats_geneWise.R, R/exprTable.R, R/getColours.R, R/glanceExprPlot.R, R/refdata.R, inst/rmd/rnasum.Rmd
Hey @JMarzec 
Thanks for pushing the changes.
I have pulled the changes from main and fixed the merge issue.
Now onto testing. I have started by testing with `batch_rm: TRUE` as this is the current default value used.
The code error out at `cdf_plots_mut` chunk with:
```
Error: Must supply `x` and `y` attributes
```
Which links to `RNAsum/R/cdfPlot.R` script - line 106, when it tries to add markers for internal cancer cohort.
```
plotly::add_markers(
y = group.z.gene[[int_cancer]]$quantile, x = group.z.gene[[int_cancer]]$z,
text = rownames(group.z.gene[[int_cancer]]),
name = int_cancer,
marker = list(size = 12, opacity = 0.5, color = "red"),
showlegend = TRUE
```
Can you double check please if this is the issue?
=> Batch effect correction
